### ISSUE TITLE
entity render distance limit

### ISSUE THREAD

**Issue by Architech35** [jimbot6000/Block-Entity-Extended-Rendering#10]
I have seen that the entity (such as banner) render limit is only about 256 blocks in my game, is it possible to increaase the number?
Thanks for any answer

**Comment by jhalfsharp** [comment]
If you use the Mod Menu mod, then you can open the mod's config page and there's a slider to change the render distance. If you don't, you can edit the config file manually in the game files. Having a better way to change the settings is on my to-do list.
