### ISSUE TITLE
Game crash when opening mod settings with YACL

### ISSUE THREAD

**Issue by orrnithogalum** [jimbot6000/Block-Entity-Extended-Rendering#14]
Game crashes with error:

```
The game crashed whilst rendering screen
Error: java.lang.NoSuchFieldError: field_22757
```
Exit code: -1

Game version 1.20.4 with other mods installed

**Comment by DepressieBeer** [comment]
i have this problem too, someone said to me: "Just looks like a bug with a library that BEER uses". any way of fixing this?

**Comment by jhalfsharp** [comment]
At the moment, BEER uses spruceUI. The next version (that I hope to release later today) uses a different library that should hopefully make it compatible.

**Comment by jhalfsharp** [comment]
Both versions 3.1.0 and 4.0.0 should have this issue fixed.

**Comment by RE4LLY-ME** [comment]
FYI, I still had the game crash when trying to access the options menu even with the updated version 3.1.0, but was able to resolve it by manually installing the right version of ObsidianUI. Now it works like a charm.
