### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [jimbot6000/Block-Entity-Extended-Rendering#16]

**Comment by Nilsson321** [comment]
^^

**Comment by HEROshineMC** [comment]
Hey @jhalfsharp I forked and updated to 1.21 :) Do you want to make a 1.21 branch before I make a pull request? My fork is [here](https://github.com/HEROshineMC/Block-Entity-Extended-Rendering/tree/1.21) (the 1.21 branch), and my commit is [here](https://github.com/HEROshineMC/Block-Entity-Extended-Rendering/commit/0fce42a83f682d954f1db71d640018dc18e54b6d). (might need some clean up)

**Comment by sternschnaube** [comment]
Thank you @HEROshineMC, could you give me please the finished build? 
I would like to test the update.

**Comment by HEROshineMC** [comment]
@sternschnaube I don't think it needs any testing, but sure :) Here you go: [block-entity-extended-rendering-4.0.0.zip](https://github.com/user-attachments/files/16454868/block-entity-extended-rendering-4.0.0.zip)

**Comment by sternschnaube** [comment]
> @sternschnaube I don't think it needs any testing, but sure :) Here you go: [block-entity-extended-rendering-4.0.0.zip](https://github.com/user-attachments/files/16454868/block-entity-extended-rendering-4.0.0.zip)

Thanks, mod works good! I keep this open until @jhalfsharp does his part 😄

**Comment by jhalfsharp** [comment]
Hey! Thanks @HEROshineMC for the maintenance, I'm hoping to get to fixing the mod later today. Sorry for the delays, I lost my java environment and most of my desktop setup when a computer crapped out on me.

**Comment by HEROshineMC** [comment]
@jhalfsharp Aww that's awful, sorry to hear that :( That's no fun. Also if you would like me to make a pull request or help let me know :)

**Comment by jhalfsharp** [comment]
4.0.0 is out on modrinth! Thanks for the patience yall.
