### ISSUE TITLE
Quilt?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [jimbot6000/Block-Entity-Extended-Rendering#7]
Just wondering if you plan on supporting quilt.

I know most fabric mods work on quilt, it's just that when downloading them from a client it makes it more of a hassle if it isn't shown there and having to look for the mod on your browser and download it from there and manually moving to the mods folder rather than from the client. Also makes updating a hassle

If you don't plan on supporting/updating to quilt that's also fine.

**Comment by Aces-and-Jacks** [comment]
Never mind. It works just didn't appear at first on the client I'm using because the label was 1.19 instead of 1.19.2

So all good

**Comment by jhalfsharp** [comment]
Gonna be honest, I never really tested it on quilt. Glad to hear it works though.
