### ISSUE TITLE
Can be marked as 1.19.3 compatible

### ISSUE THREAD

**Issue by sternschnaube** [jimbot6000/Block-Entity-Extended-Rendering#9]

**Comment by Cyclopropinon** [comment]
also 1.19.4?

**Comment by jhalfsharp** [comment]
ive been meaning to get to these, but school is ramping up for finals. Hopefully ill be able to update the mod substantially over summer.

**Comment by sternschnaube** [comment]
I'm currently not sure if the mod works for 1.19.4 @Cyclopropinon.

Good to hear @jimbot6000, take your time - I'm looking forward to the 1.20 release 😊

**Comment by sternschnaube** [comment]
Thanks for the 1.20 version 🥳

**Comment by jhalfsharp** [comment]
No problem 👍 reopening because the original issue was about later 1.19 versions and i havent tested those yet

**Comment by jhalfsharp** [comment]
Went back and finally tested on all versions 1.19+ on both fabric and quilt, and updated the modrinth listing accordingly.
